/** Veloraq expense-comment API — stable `error.code` values we branch on in UI. */
export const EXPENSE_COMMENT_SERVICE_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EXPENSE_CURSOR: 'INVALID_EXPENSE_CURSOR',
  EXPENSE_COMMENT_INVALID_PARENT: 'EXPENSE_COMMENT_INVALID_PARENT',
  NOT_GROUP_MEMBER: 'NOT_GROUP_MEMBER',
  EXPENSE_COMMENT_FORBIDDEN: 'EXPENSE_COMMENT_FORBIDDEN',
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  EXPENSE_COMMENT_NOT_FOUND: 'EXPENSE_COMMENT_NOT_FOUND',
} as const;

export type ExpenseCommentServiceCode =
  (typeof EXPENSE_COMMENT_SERVICE_CODES)[keyof typeof EXPENSE_COMMENT_SERVICE_CODES];
