import { StyleSheet } from 'react-native';

import { radius, size, space, textStyles, typography } from '@/theme';

export const addGroupMemberModalStyles = StyleSheet.create({
  flex: { flex: 1 },
  keyboard: { flex: 1 },
  header: {
    paddingHorizontal: space.screenPadding,
    paddingTop: space.gapSm,
    paddingBottom: space.gapMd,
    alignItems: 'center',
    gap: space.gapXs,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
  },
  cancelBtn: {
    minWidth: 72,
    paddingVertical: space.gapSm,
    paddingHorizontal: space.gapSm,
  },
  headerSpacer: {
    minWidth: 72,
  },
  screenHeader: {
    paddingHorizontal: space.screenPadding,
    paddingTop: space.gapSm,
    paddingBottom: space.gapMd,
    alignItems: 'stretch',
    gap: space.gapXs,
  },
  screenHeaderTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  screenHeaderKickers: {
    gap: space.gapXs,
    marginBottom: space.gapXs,
  },
  screenTitle: {
    ...textStyles.h2,
    fontSize: typography.fontSize['2xl'],
    fontWeight: '700',
    textAlign: 'left',
    letterSpacing: typography.letterSpacing.tight,
  },
  screenSubtitle: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    textAlign: 'left',
    lineHeight: 20,
    maxWidth: 340,
  },
  title: {
    ...textStyles.h2,
    fontSize: typography.fontSize['2xl'],
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: typography.letterSpacing.tight,
  },
  subtitle: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: 280,
  },
  scroll: {
    flex: 1,
    alignSelf: 'stretch',
  },
  body: {
    flexGrow: 1,
    paddingTop: space.gapMd,
    gap: space.sectionGapSm,
  },
  contactsCard: {
    alignSelf: 'stretch',
    padding: space.gapLg,
    borderRadius: radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    gap: space.gapMd,
  },
  contactsCardTitle: {
    ...textStyles.h3,
    fontSize: typography.fontSize.lg,
    fontWeight: '700',
    letterSpacing: typography.letterSpacing.tight,
  },
  contactsCardBody: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    lineHeight: 20,
  },
  contactsAllowBtn: {
    alignSelf: 'stretch',
    minHeight: 48,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: space.gapLg,
  },
  contactsAllowLabel: {
    ...textStyles.label,
    fontSize: typography.fontSize.base,
    fontWeight: '700',
  },
  searchShell: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapMd,
    minHeight: 54,
    paddingHorizontal: space.gapMd,
    borderRadius: radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
  },
  searchInput: {
    flex: 1,
    ...textStyles.body,
    fontSize: typography.fontSize.base,
    paddingVertical: space.gapSm,
    margin: 0,
    minWidth: 0,
  },
  segmentWrap: {
    height: 48,
    borderRadius: radius.full,
    padding: 4,
    alignSelf: 'stretch',
    position: 'relative',
    overflow: 'hidden',
  },
  segmentThumb: {
    position: 'absolute',
    left: 0,
    top: 4,
    bottom: 4,
    borderRadius: radius.full,
    zIndex: 0,
  },
  segmentRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    zIndex: 1,
  },
  segmentTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.full,
  },
  segmentTabLabel: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
  },
  phoneShellBox: {
    borderRadius: radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: space.gapXs,
    paddingHorizontal: space.gapSm,
    alignSelf: 'stretch',
    minHeight: 56,
  },
  manualFieldShell: {
    borderRadius: radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    minHeight: 54,
    paddingHorizontal: space.gapMd,
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  manualFieldInput: {
    ...textStyles.body,
    fontSize: typography.fontSize.lg,
    paddingVertical: space.gapSm,
    margin: 0,
  },
  sectionTitle: {
    ...textStyles.h3,
    fontSize: typography.fontSize.base,
    fontWeight: '700',
    letterSpacing: typography.letterSpacing.tight,
  },
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapMd,
    paddingVertical: space.gapMd,
    paddingHorizontal: space.gapMd,
    borderRadius: radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    minHeight: size.touchMin + space.gapSm,
  },
  userAvatar: {
    width: 48,
    height: 48,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  userAvatarImg: {
    width: 48,
    height: 48,
    borderRadius: radius.full,
  },
  userAvatarGlyph: {
    fontSize: 18,
    fontWeight: '700',
  },
  userTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  userName: {
    ...textStyles.bodyMedium,
    fontSize: typography.fontSize.base,
  },
  userHandle: {
    ...textStyles.captionSmall,
    fontSize: typography.fontSize.sm,
  },
  rowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapSm,
    flexShrink: 0,
  },
  rowAction: {
    minWidth: 88,
    height: 40,
    paddingHorizontal: space.gapMd,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  rowShareAction: {
    minWidth: 76,
    height: 40,
    paddingHorizontal: space.gapSm,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  rowActionLabel: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
  },
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: space.sectionGap,
    paddingHorizontal: space.gapLg,
    gap: space.gapMd,
    alignSelf: 'stretch',
  },
  emptyGlyph: {
    width: 88,
    height: 88,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  emptyTitle: {
    ...textStyles.h3,
    fontSize: typography.fontSize.lg,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyBody: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: 280,
  },
  errorBanner: {
    padding: space.gapMd,
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
  },
  errorText: {
    ...textStyles.caption,
    fontSize: typography.fontSize.sm,
  },
  footer: {
    paddingTop: space.gapMd,
    paddingHorizontal: space.screenPadding,
    alignSelf: 'stretch',
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  footerCta: {
    minHeight: 54,
    borderRadius: radius['2xl'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerCtaLabel: {
    ...textStyles.bodyLarge,
    fontWeight: '700',
    fontSize: typography.fontSize.base,
  },
  inlineLoading: {
    marginVertical: space.gapSm,
    alignSelf: 'center',
  },
});
