import { StyleSheet } from 'react-native';

import { radius, size, space, textStyles, typography } from '@/theme';

/** Add-members — Nothing OS: airy layout, thin borders, minimal chrome. */
export const addGroupMemberModalStyles = StyleSheet.create({
  flex: { flex: 1 },
  keyboard: { flex: 1 },
  header: {
    paddingHorizontal: space.screenPadding,
    paddingTop: space.gapMd,
    paddingBottom: space.gapLg,
    alignItems: 'stretch',
    gap: space.gapSm,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
  },
  cancelBtn: {
    minWidth: 72,
    paddingVertical: space.gapSm,
    paddingHorizontal: space.gapSm,
  },
  headerSpacer: {
    minWidth: 72,
  },
  screenHeader: {
    paddingHorizontal: space.screenPadding,
    paddingTop: space.sectionGap,
    paddingBottom: space.gapLg,
    alignItems: 'stretch',
    gap: space.gapXs,
  },
  screenHeaderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  screenHeaderBrandKicker: {
    flexShrink: 1,
    marginLeft: space.gapXs,
    textAlign: 'left',
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize['2xs'],
    lineHeight: typography.fontSize['2xs'] * typography.lineHeight.normal,
    letterSpacing: typography.fontSize['2xs'] * 0.18,
    textTransform: 'uppercase',
  },
  specStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: space.gapXs,
  },
  specDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
  },
  screenTitle: {
    fontFamily: typography.fontFamily.sans.semiBold,
    fontSize: typography.fontSize['3xl'],
    lineHeight: typography.fontSize['3xl'] * typography.lineHeight.tight,
    textAlign: 'left',
    letterSpacing: typography.letterSpacing.tight,
    marginTop: space.gapMd,
  },
  screenSubtitle: {
    fontFamily: typography.fontFamily.sans.regular,
    fontSize: typography.fontSize.sm,
    textAlign: 'left',
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    maxWidth: 320,
    letterSpacing: typography.letterSpacing.normal,
    marginTop: space.gapXs,
  },
  title: {
    fontFamily: typography.fontFamily.sans.semiBold,
    fontSize: typography.fontSize['3xl'],
    lineHeight: typography.fontSize['3xl'] * typography.lineHeight.tight,
    textAlign: 'left',
    letterSpacing: typography.letterSpacing.tight,
    marginTop: space.gapXs,
  },
  subtitle: {
    fontFamily: typography.fontFamily.sans.regular,
    fontSize: typography.fontSize.sm,
    textAlign: 'left',
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    maxWidth: 400,
  },
  scroll: {
    flex: 1,
    alignSelf: 'stretch',
  },
  body: {
    flexGrow: 1,
    paddingTop: space.gapLg,
    gap: space.gapLg,
  },
  contactsCard: {
    alignSelf: 'stretch',
    padding: space.gapLg,
    borderRadius: radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    gap: space.gapMd,
  },
  contactsCardTitle: {
    fontFamily: typography.fontFamily.sans.semiBold,
    fontSize: typography.fontSize.md,
    letterSpacing: typography.letterSpacing.tight,
    lineHeight: typography.fontSize.md * typography.lineHeight.snug,
  },
  contactsCardBody: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
  },
  contactsAllowBtn: {
    alignSelf: 'stretch',
    minHeight: 52,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: space.gapLg,
    borderWidth: StyleSheet.hairlineWidth,
  },
  contactsAllowLabel: {
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize.sm,
    letterSpacing: typography.letterSpacing.widest,
    textTransform: 'uppercase',
  },
  contactsInline: {
    alignSelf: 'stretch',
    gap: space.gapSm,
    paddingTop: space.gapXs,
  },
  contactsInlineTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapSm,
  },
  contactsInlineTitle: {
    flex: 1,
    fontFamily: typography.fontFamily.sans.medium,
    fontSize: typography.fontSize.sm,
    letterSpacing: typography.letterSpacing.tight,
    lineHeight: typography.fontSize.sm * typography.lineHeight.snug,
  },
  contactsInlineBody: {
    fontFamily: typography.fontFamily.sans.regular,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    letterSpacing: typography.letterSpacing.normal,
  },
  contactsInlineCta: {
    alignSelf: 'flex-start',
    marginTop: space.gapXs,
    minHeight: 44,
    paddingHorizontal: space.gapLg,
    paddingVertical: space.gapSm,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactsInlineCtaLabel: {
    fontSize: typography.fontSize['2xs'],
    letterSpacing: typography.letterSpacing.widest,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize['2xs'],
    letterSpacing: typography.fontSize['2xs'] * 0.18,
    textTransform: 'uppercase',
    marginBottom: space.gapSm,
  },
  suggestionBlock: {
    alignSelf: 'stretch',
    gap: space.gapMd,
  },
  suggestionHairline: {
    height: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    marginLeft: 40 + space.gapMd,
  },
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapMd,
    paddingVertical: space.gapMd,
    paddingHorizontal: 0,
    alignSelf: 'stretch',
    minHeight: size.touchMin,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  userAvatarGlyph: {
    fontSize: 16,
    fontFamily: typography.fontFamily.sans.semiBold,
  },
  userTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  userName: {
    fontFamily: typography.fontFamily.sans.medium,
    fontSize: typography.fontSize.sm,
  },
  userHandle: {
    fontFamily: typography.fontFamily.mono.regular,
    fontSize: typography.fontSize['2xs'],
  },
  rowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapSm,
    flexShrink: 0,
  },
  rowAction: {
    minWidth: 88,
    height: 40,
    paddingHorizontal: space.gapMd,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  rowShareAction: {
    minWidth: 76,
    height: 40,
    paddingHorizontal: space.gapSm,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  rowActionLabel: {
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize['2xs'],
    fontWeight: '600',
    letterSpacing: typography.letterSpacing.wide,
    textTransform: 'uppercase',
  },
  emptyWrap: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: space.gap,
    alignSelf: 'stretch',
  },
  emptyPanel: {
    alignSelf: 'stretch',
    borderRadius: radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    padding: space.gapLg,
    gap: space.gap,
  },
  emptyGlyph: {
    width: 56,
    height: 56,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  emptyTitle: {
    fontFamily: typography.fontFamily.sans.semiBold,
    fontSize: typography.fontSize.md,
    textAlign: 'left',
    letterSpacing: typography.letterSpacing.tight,
    lineHeight: typography.fontSize.md * typography.lineHeight.snug,
  },
  emptyBody: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    textAlign: 'left',
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    maxWidth: 320,
  },
  errorBanner: {
    padding: space.gapMd,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
  },
  errorText: {
    ...textStyles.caption,
    fontSize: typography.fontSize.sm,
  },
  footer: {
    paddingTop: space.gapMd,
    paddingHorizontal: space.screenPadding,
    alignSelf: 'stretch',
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  footerCta: {
    minHeight: 52,
    borderRadius: radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  footerCtaLabel: {
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize.sm,
    letterSpacing: typography.letterSpacing.widest,
    textTransform: 'uppercase',
  },
  inlineLoading: {
    marginVertical: space.gapSm,
    alignSelf: 'flex-start',
  },
});
