import { StyleSheet } from 'react-native';

import { radius, size, space, spacing, textStyles, typography } from '@/theme';

export const groupDetailScreenStyles = StyleSheet.create({
  safe: { flex: 1 },
  scroll: {
    paddingTop: 0,
  },
  hubHeaderStack: {
    alignSelf: 'stretch',
    gap: 0,
  },
  hubSectionStack: {
    alignSelf: 'stretch',
    gap: space.sectionGap,
  },
  hubNavBarBlur: {
    alignSelf: 'stretch',
    paddingBottom: space.gapXs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
  },
  hero: {
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  heroAvatarBlock: {
    marginTop: space.gapLg,
    alignItems: 'center',
  },
  heroTitleBlock: {
    marginTop: space.gap,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  heroFirstMetaBlock: {
    marginTop: space.gapSm,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  hubMoodLine: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
    fontWeight: '500',
  },
  hubMemberLine: {
    ...textStyles.captionSmall,
    fontFamily: typography.fontFamily.mono.regular,
    fontSize: typography.fontSize.sm,
    textAlign: 'center',
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    letterSpacing: typography.letterSpacing.wide,
    alignSelf: 'stretch',
  },
  heroSubtitleLine: {
    marginTop: space.gapXs,
  },
  hubPeopleLinkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: space.gapSm,
    marginTop: space.gapSm,
  },
  hubPeopleLink: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  balanceCard: {
    alignSelf: 'stretch',
    borderRadius: radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: space.gapMd,
    paddingHorizontal: space.gapMd,
    gap: space.gapSm,
    maxHeight: spacing['40'],
    overflow: 'hidden',
    justifyContent: 'center',
  },
  balanceKicker: {
    ...textStyles.overline,
    fontSize: typography.fontSize.screenSection,
    fontFamily: typography.fontFamily.mono.medium,
    lineHeight: typography.fontSize.screenSection * typography.lineHeight.normal,
  },
  balanceValue: {
    ...textStyles.bodyLarge,
    fontSize: typography.fontSize['2xl'],
    lineHeight: typography.fontSize['2xl'] * typography.lineHeight.tight,
    fontWeight: '600',
    letterSpacing: typography.letterSpacing.tight,
  },
  sectionRule: {
    height: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
  },
  sectionKicker: {
    ...textStyles.overline,
    fontSize: typography.fontSize.screenSection,
    fontFamily: typography.fontFamily.mono.medium,
    lineHeight: typography.fontSize.screenSection * typography.lineHeight.normal,
    letterSpacing: typography.letterSpacing.widest,
    alignSelf: 'stretch',
  },
  quickActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: space.gapMd,
    alignSelf: 'stretch',
  },
  quickActionPill: {
    flexGrow: 1,
    flexBasis: 0,
    minWidth: spacing['7'],
    borderRadius: radius.full,
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: space.gapSm,
    paddingHorizontal: space.gapSm,
    minHeight: size.touchMin,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  quickActionLabel: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  activityStack: {
    alignSelf: 'stretch',
    gap: space.gapMd,
  },
  activityCard: {
    alignSelf: 'stretch',
    borderRadius: radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    paddingVertical: space.gapMd,
    paddingHorizontal: space.gapMd,
    gap: space.gapSm,
    overflow: 'hidden',
  },
  activityPaidLine: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.tight,
    fontWeight: '600',
    letterSpacing: typography.letterSpacing.tight,
  },
  activityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapSm,
    flexWrap: 'wrap',
  },
  activityTitleEmoji: {
    fontSize: typography.fontSize.lg,
    lineHeight: spacing['6'],
  },
  activityTitleText: {
    ...textStyles.body,
    fontSize: typography.fontSize.base,
    lineHeight: typography.fontSize.base * typography.lineHeight.tight,
    fontWeight: '500',
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  activityClockLine: {
    ...textStyles.captionSmall,
    fontFamily: typography.fontFamily.mono.regular,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    letterSpacing: typography.letterSpacing.wide,
  },
  activitySplitLine: {
    ...textStyles.captionSmall,
    fontFamily: typography.fontFamily.mono.regular,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    letterSpacing: typography.letterSpacing.wide,
  },
  balanceListRow: {
    alignSelf: 'stretch',
  },
  memberStripScroll: {
    flexGrow: 0,
  },
  memberStripRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapSm,
    alignSelf: 'stretch',
  },
  memberStripAvatar: {
    width: spacing['10'],
    height: spacing['10'],
    borderRadius: radius.full,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberStripAvatarMore: {
    ...textStyles.captionSmall,
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
  },
  memberStripFallbackLetter: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
  },
  memberStripChevronHit: {
    padding: space.gapSm,
    marginRight: -space.gapSm,
  },
  heroIconCluster: {
    position: 'relative',
    width: spacing['24'],
    height: spacing['24'],
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroIconGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radius.full,
  },
  heroAvatarWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroAvatarRing: {
    width: spacing['24'],
    height: spacing['24'],
    borderRadius: radius.full,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth * 2,
  },
  heroAvatarImage: {
    width: spacing['24'],
    height: spacing['24'],
  },
  heroAvatarFallback: {
    width: spacing['24'],
    height: spacing['24'],
    borderRadius: radius.full,
    borderWidth: StyleSheet.hairlineWidth * 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroEmoji: {
    fontSize: typography.fontSize['4xl'],
    lineHeight: typography.fontSize['4xl'] * typography.lineHeight.tight,
  },
  heroTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: spacing['2'],
    paddingHorizontal: space.gapSm,
  },
  heroMemberRowWrap: {
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  heroMemberRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: space.gapSm,
    maxWidth: '100%',
  },
  heroMemberFaceStack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroMemberFace: {
    width: spacing['10'],
    height: spacing['10'],
    borderRadius: radius.full,
    borderWidth: StyleSheet.hairlineWidth * 2,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroMemberFaceOverlap: {
    marginLeft: -spacing['3'],
  },
  heroMemberFaceFallbackLetter: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
    fontWeight: '600',
  },
  heroMemberOverflowMono: {
    ...textStyles.captionSmall,
    fontFamily: typography.fontFamily.mono.regular,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.relaxed,
    letterSpacing: typography.letterSpacing.wide,
    flexShrink: 1,
  },
  heroTitleEmoji: {
    fontSize: typography.fontSize['3xl'],
    lineHeight: spacing['10'],
  },
  heroTitleName: {
    ...textStyles.h1,
    fontSize: typography.fontSize.hubTitle,
    lineHeight: typography.fontSize.hubTitle * typography.lineHeight.tight,
    fontWeight: '600',
    letterSpacing: typography.letterSpacing.tight,
    textAlign: 'center',
    flexShrink: 1,
  },
  title: {
    ...textStyles.h1,
    fontSize: typography.fontSize.hubTitle,
    lineHeight: typography.fontSize.hubTitle * typography.lineHeight.tight,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: typography.letterSpacing.tight,
  },
  sectionBlock: {
    alignSelf: 'stretch',
    gap: space.gapMd,
  },
  sectionTitle: {
    ...textStyles.h3,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.tight,
    fontWeight: '600',
    letterSpacing: typography.letterSpacing.tight,
  },
  emptyHint: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
  },
  hubExpensesEmptyBlock: {
    alignSelf: 'stretch',
    gap: space.gapSm,
  },
  hubExpensesEmptyTitle: {
    ...textStyles.body,
    fontSize: typography.fontSize.base,
    lineHeight: typography.fontSize.base * typography.lineHeight.tight,
    fontWeight: '600',
    letterSpacing: typography.letterSpacing.tight,
  },
  hubExpensesEmptyBody: {
    ...textStyles.body,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.normal,
  },
  metaCard: {
    borderRadius: radius['2xl'],
    borderWidth: StyleSheet.hairlineWidth,
    padding: space.gapLg,
    gap: space.gapSm,
    alignSelf: 'stretch',
  },
  metaLabel: {
    ...textStyles.overline,
  },
  metaValue: {
    ...textStyles.bodyLarge,
  },
  metaValueMono: {
    ...textStyles.body,
    fontFamily: typography.fontFamily.mono.regular,
    fontSize: typography.fontSize.sm,
    letterSpacing: typography.letterSpacing.wide,
  },
  overflowHit: {
    marginRight: -space.gapSm,
    padding: space.gapSm,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: size.touchMin,
    minHeight: size.touchMin,
  },
  overflowPressableFill: {
    flex: 1,
    alignSelf: 'stretch',
    minWidth: size.touchMin,
    minHeight: size.touchMin,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hairline: {
    height: StyleSheet.hairlineWidth,
    marginVertical: space.gapSm,
    alignSelf: 'stretch',
  },
  modalRoot: {
    flex: 1,
  },
  menuBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  menuCard: {
    position: 'absolute',
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    minWidth: 216,
    maxWidth: 280,
    overflow: 'hidden',
  },
  menuRowPressable: {
    width: '100%',
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.gapMd,
    paddingVertical: space.gapMd,
    paddingHorizontal: space.gapMd,
    minHeight: size.touchMin,
  },
  menuRowLabel: {
    ...textStyles.body,
    flex: 1,
    flexShrink: 1,
  },
  menuDivider: {
    height: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
  },
  aboutCenterWrap: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: space.screenPadding,
    paddingVertical: space.sectionGap,
  },
  aboutInner: {
    gap: space.gapLg,
    alignSelf: 'stretch',
  },
  aboutHeading: {
    ...textStyles.h3,
    letterSpacing: typography.letterSpacing.tight,
  },
  mainColumn: {
    flex: 1,
  },
  expenseFabAnchor: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    pointerEvents: 'box-none',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  expenseFab: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    flexShrink: 0,
    gap: space.gapSm,
    paddingVertical: space.gapMd,
    paddingHorizontal: space.gapLg,
    minHeight: size.touchMin,
    borderRadius: radius.full,
    borderWidth: StyleSheet.hairlineWidth,
    maxWidth: '92%',
  },
  expenseFabLabel: {
    ...textStyles.overline,
    fontFamily: typography.fontFamily.mono.medium,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.fontSize.sm * typography.lineHeight.tight,
    letterSpacing: typography.letterSpacing.widest,
    flexShrink: 1,
  },
  logSheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  logSheetGrab: {
    width: spacing['9'],
    height: spacing['1'],
    borderRadius: radius.full,
    alignSelf: 'center',
    marginBottom: space.gapSm,
  },
  logSheetPaper: {
    width: '100%',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: 0,
    paddingTop: space.gapSm,
    paddingHorizontal: space.screenPadding,
    gap: space.gapLg,
  },
  logSheetTitleBlock: {
    alignSelf: 'stretch',
    gap: space.gapSm,
  },
  logSheetKicker: {
    ...textStyles.overline,
    fontFamily: typography.fontFamily.mono.medium,
    letterSpacing: typography.letterSpacing.widest,
  },
  logSheetTitle: {
    ...textStyles.h3,
    letterSpacing: typography.letterSpacing.tight,
  },
  logSheetOptionList: {
    alignSelf: 'stretch',
    gap: space.gapSm,
  },
  logSheetOptionPress: {
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  logSheetOptionInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space.gapMd,
    paddingVertical: space.gapMd,
    paddingHorizontal: space.gapMd,
    minHeight: size.touchMin,
  },
  logSheetOptionLabel: {
    ...textStyles.body,
    flex: 1,
    fontWeight: '600',
  },
  logSheetSoonBody: {
    ...textStyles.body,
    alignSelf: 'stretch',
    lineHeight: 22,
  },
  logSheetFooter: {
    alignSelf: 'stretch',
    gap: space.gapMd,
    marginBottom: space.gapSm,
  },
  logSheetLinkPress: {
    alignSelf: 'center',
    paddingVertical: space.gapSm,
    paddingHorizontal: space.gapMd,
  },
  logSheetLinkLabel: {
    ...textStyles.label,
    fontSize: typography.fontSize.sm,
  },
});
